endpoint:
  - wss://rpc.ibp.network/polkadot
  - wss://polkadot-rpc.dwellir.com
mock-signature-host: true
block: ${env.POLKADOT_BLOCK_NUMBER}
db: ./dbs/polkadot.sqlite
runtime-log-level: 5

wasm-override: ./runtime_wasm/polkadot_runtime.compact.compressed.wasm
# resume: true

import-storage:
  System:
    Account:
      - [[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { providers: 1, data: { free: 1000000000000000 }}]
  ParasDisputes:
    $removePrefix: ['disputes'] # those can makes block building super slow
