endpoint: wss://polkadot-asset-hub-rpc.polkadot.io
mock-signature-host: true
block: ${env.POLKADOT_ASSET_HUB_BLOCK_NUMBER}
db: ./dbs/polkadot-asset-hub.sqlite
runtime-log-level: 5

wasm-override: ./runtime_wasm/asset_hub_polkadot_runtime.compact.compressed.wasm
# resume: ${env.POLKADOT_ASSET_HUB_BLOCK_NUMBER}

import-storage:
  System:
    Account:
      - [[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { providers: 1, data: { free: 1000000000000000 }}]
  Assets:
    Account:
      - [[1984, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
    Asset: [[[1984], { supply: 1000000000 }]]

